Mqtt:
  Host: 127.0.0.1
  Port: 1883
  Password:
  Username:
  Qos: 0
  UpTopic: /twwg/serial/up
  DownTopic: /twwg/serial/down
Serial:
  Address: /dev/ttyUSB0
  BaudRate: 115200
  DataBits: 8
  StopBits: 1
  Parity: N
  BufferSize: 16
  UnpackBufferSize: 512
  UnpackBHead: [ 0x24, 0x50, 0x41, 0x52, 0x41 ]